def painosso():
    print("Pai nosso que estais no céu")
    print("Santificado seja o vosso nome")
    print("Venha a nós o vosso reino")
    print("Seja feita a vossa vontade")
    print("Assim na terra como no céu")
    print("O pão nosso de cada dia nos dai hoje")
    print("Perdoai as nossas ofensas")
    print("Assim como nós perdoamos a quem nos tem ofendido")
    print("E não nos deixeis cair em tentação")
    print("Mas livrai-nos do mal")
    print("Amém")
def Avemaria():
    print("Ave Maria cheia de graça")
    print("O Senhor é convosco")
    print("Bendita sois vós entre as mulheres")
    print("E bendito é o fruto do vosso ventre, Jesus")
    print("Santa Maria, Mãe de Deus")
    print("Rogai por nós pecadores")
    print("Agora e na hora de nossa morte")
    print("Amém")